# inside .github/workflows/action.yml
name: Deploy branch to DigitalOcean
on:
  push:
    branches-ignore:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: yarn

      - name: Build dist
        run: yarn dist

      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1

      - run: "echo branch is ${BRANCH_NAME}"

      - name: Upload to DigitalOcean
        uses: play-curious/do-space-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: ./dist/
          DEST_DIR: ${{ env.BRANCH_NAME }}
          SPACE_NAME: ${{ secrets.SPACE_NAME }}
          SPACE_REGION: ${{ secrets.SPACE_REGION }}
          SPACE_ACCESS_KEY_ID: ${{ secrets.SPACE_ACCESS_KEY_ID }}
          SPACE_SECRET_ACCESS_KEY: ${{ secrets.SPACE_SECRET_ACCESS_KEY }}
